//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MrFlixMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class CheckOutRecord
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CheckOutRecord()
        {
            this.MovieLineItems = new HashSet<MovieLineItem>();
        }
    
        public int OrderID { get; set; }
        public int CheckOutEmployeeID { get; set; }
        public string MovieTitle { get; set; }
        public string CustomerID { get; set; }
        public System.DateTime DateCheckedOut { get; set; }
        public Nullable<int> CheckInEmployeeID { get; set; }
        public Nullable<System.DateTime> DateCheckedIn { get; set; }
        public bool Active { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Employee Employee1 { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Movy Movy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MovieLineItem> MovieLineItems { get; set; }
    }
}
