//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MrFlixMVC
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MrFlixVideoRentalsEntities : DbContext
    {
        public MrFlixVideoRentalsEntities()
            : base("name=MrFlixVideoRentalsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CheckOutRecord> CheckOutRecords { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Genre> Genres { get; set; }
        public virtual DbSet<MovieLineItem> MovieLineItems { get; set; }
        public virtual DbSet<Movy> Movies { get; set; }
        public virtual DbSet<ReviewRecord> ReviewRecords { get; set; }
    }
}
